AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  BcPubLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.handler
      Runtime: nodejs18.x
      Role: !GetAtt BcPubLambdaRole.Arn
      CodeUri: broadcast-pub/
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Sub "arn:aws:sns:us-east-1:${AWS::AccountId}:BroadcastTopic"
      Policies:
        - SNSPublishPolicy:
          TopicName: !Ref BroadcastTopic
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /publish
            Method: post
            RestApiId:
              Ref: BroadcastApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts

  BroadcastApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: prod
      Auth:
        ApiKeyRequired: false

  BcPubLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      Policies:
        - PolicyName: SNSPublishPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sns:Publish
                Resource: !Sub "arn:aws:sns:us-east-1:${AWS::AccountId}:BroadcastTopic"

Outputs:
  BroadcastApiEndpoint:
    Description: "URL of the API endpoint"
    Value: !Sub "https://${BroadcastApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
    Export:
      Name: !Sub "${AWS::StackName}-BroadcastApiEndpoint"